# Generated by Django 5.0 on 2023-12-28 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bobyard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
