# Generated by Django 5.0 on 2023-12-28 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bobyard', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
