# Generated by Django 5.0 on 2023-12-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobyard', '0011_alter_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='unknown', max_length=20),
            preserve_default=False,
        ),
    ]
