# Generated by Django 5.0 on 2023-12-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobyard', '0013_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(default='no time available'),
        ),
    ]
