# Generated by Django 5.0 on 2023-12-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobyard', '0015_rename_body_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_edited',
            field=models.CharField(blank=True),
        ),
    ]
