# Generated by Django 5.0 on 2023-12-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobyard', '0016_post_last_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='last_edited',
        ),
        migrations.RemoveField(
            model_name='post',
            name='time',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(default='empty'),
            preserve_default=False,
        ),
    ]
