# Generated by Django 5.0 on 2023-12-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobyard', '0018_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
