# Generated by Django 5.0 on 2023-12-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobyard', '0021_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(),
        ),
    ]
