# Generated by Django 5.0 on 2023-12-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobyard', '0022_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(default=None),
        ),
    ]
