# Generated by Django 5.0 on 2023-12-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobyard', '0026_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(),
        ),
    ]
