# Generated by Django 5.0 on 2023-12-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobyard', '0027_alter_post_author_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default=None, max_length=500, upload_to=''),
        ),
    ]
