# Generated by Django 5.0 on 2023-12-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobyard', '0028_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(default=None, max_length=500),
        ),
    ]
