# Generated by Django 5.0 on 2023-12-31 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobyard', '0034_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
