# Generated by Django 5.0 on 2023-12-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobyard', '0036_alter_profile_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.CharField(default=''),
        ),
    ]
