# Generated by Django 5.0 on 2024-01-02 02:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobyard', '0037_post_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
    ]
