# Generated by Django 5.0 on 2024-01-02 02:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobyard', '0039_alter_post_likers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
