# Generated by Django 5.0 on 2024-01-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobyard', '0040_alter_post_likers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likers',
        ),
        migrations.AddField(
            model_name='post',
            name='likers',
            field=models.ManyToManyField(default=list, to='bobyard.profile'),
        ),
    ]
