# Generated by Django 5.0 on 2024-01-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobyard', '0041_remove_post_likers_post_likers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likers',
            field=models.ManyToManyField(blank=True, to='bobyard.profile'),
        ),
    ]
